### ISSUE TITLE
Add support for autopay/auto-accept on requests from trusted friends

### ISSUE THREAD

**Issue by zdhickman** [golf1052/VenmoForSlack#10]
Having autopay/auto-accept for recurring requests from trusted friends would be nice.

Maybe we could leverage existing friends on Venmo, or maybe it's better to set this in the integration

Ideas:
- Setting a limit for the max amount to auto-accept
- Configure to match an exact amount with a trusted friend
- Configure to match an exact amount AND message with a trusted friend

**Comment by golf1052** [comment]
Syntax

`/venmo autopay add user <is/=/==> <Venmo username/alias> and amount <is/=/==/</<=> "amount" and <note/message> <is/=/==> "note"`

There will also be a list and delete command

**Comment by golf1052** [comment]
Almost 1 year old issue finally closed 🥹

**Comment by zdhickman** [comment]
My quality of life has increased
